"""sixth commit

Revision ID: 06111b9766b1
Revises: abf764d25360
Create Date: 2024-09-23 15:02:18.619554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06111b9766b1'
down_revision = 'abf764d25360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_datetime', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_datetime')

    # ### end Alembic commands ###
