"""seventh commit

Revision ID: 648d1c830e57
Revises: 06111b9766b1
Create Date: 2024-09-23 15:03:21.192499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648d1c830e57'
down_revision = '06111b9766b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_datetime', sa.String(length=150), nullable=True))
        batch_op.drop_column('registration_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_datetime', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('registration_datetime')

    # ### end Alembic commands ###
