"""empty message

Revision ID: c0a2b15a3e70
Revises: cce839ccde77
Create Date: 2024-10-27 21:49:41.412791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a2b15a3e70'
down_revision = 'cce839ccde77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_car')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_car',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('short_description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('setting1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('setting2', sa.VARCHAR(length=100), nullable=False),
    sa.Column('setting3', sa.VARCHAR(length=100), nullable=False),
    sa.Column('setting4', sa.VARCHAR(length=100), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('director', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
