"""last_version_new

Revision ID: cce839ccde77
Revises: 76ce64b384de
Create Date: 2024-10-27 21:33:34.858686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce839ccde77'
down_revision = '76ce64b384de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_car')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('short_description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('setting1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('setting2', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('setting3', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('setting4', sa.String(length=100), nullable=False))
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('make')
        batch_op.drop_column('image_file')
        batch_op.drop_column('description')
        batch_op.drop_column('main_settings')
        batch_op.drop_column('model')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_column('text')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('main_settings', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('make', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('setting4')
        batch_op.drop_column('setting3')
        batch_op.drop_column('setting2')
        batch_op.drop_column('setting1')
        batch_op.drop_column('short_description')
        batch_op.drop_column('image_url')
        batch_op.drop_column('name')

    op.create_table('_alembic_tmp_car',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('short_description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('setting1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('setting2', sa.VARCHAR(length=100), nullable=False),
    sa.Column('setting3', sa.VARCHAR(length=100), nullable=False),
    sa.Column('setting4', sa.VARCHAR(length=100), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('director', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
