"""Added reviews and car details

Revision ID: ff7b5d204bd4
Revises: 1f419137d038
Create Date: 2024-10-13 15:47:21.910065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7b5d204bd4'
down_revision = '1f419137d038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('main_settings', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('main_settings')
        batch_op.drop_column('director')

    op.drop_table('review')
    # ### end Alembic commands ###
